#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code from apache-access.log
awk 'NF>=9 {count[$1,$9]++} END {for (i in count) {split(i, a, SUBSEP); print count[i], a[1], a[2]}}' apache-access.log | sort -rn
