#!/usr/bin/env bash
# Script to display number of occurrences per IP and HTTP code

awk '{print $1, $9}' apache-access.log | \
awk '{count[$1" "$2]++} END {for (i in count) printf "%5d %s\n", count[i], i}' | \
sort -nr
