#!/usr/bin/env bash
# This script loops from 1 to 10
# Displays "bad luck" on the 4th iteration
# Displays "good luck" on the 8th iteration
# Displays "Best School" for all other iterations

count=1
while [ $count -le 10 ]
do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((count++))
done
